### ISSUE TITLE
Linear Algebra Functions & Data Structures

### ISSUE THREAD

**Issue by El-Draco** [El-Draco/miniRT#1]

**Comment by Zunon** [comment]
structs and related functions to be implemented:

t_vec2 - 2 dimensional vector (float[2])
 - [x] t_vec2 add_vec2 (t_vec2, t_vec2) - Vector addition
 - [x] t_vec2 sub_vec2 (t_vec2, t_vec2) - Vector subtraction
 - [ ] float dot_vec2 (t_vec2, t_vec2) - Dot product
 - [ ] t_vec3 cross_vec2 (t_vec2, t_vec2) - Cross product
 - [ ] t_vec2 scale_vec2 (t_vec2, float) - Scalar multiplication

t_vec3 - 3 dimensional vector (float[3])
 - [x] t_vec3 add_vec3 (t_vec3, t_vec3)
 - [x] t_vec3 sub_vec3 (t_vec3, t_vec3)
 - [x] float dot_vec3 (t_vec3, t_vec3)
 - [x] t_vec3 cross_vec3 (t_vec3, t_vec3)
 - [x] t_vec3 scale_vec3 (t_vec3, float)
 - [ ] t_vec3 normalize_vec3 (t_vec3)

t_hvec - homogenous vector with 4 components
 - [ ] t_hvec add_hvec (t_hvec, t_hvec)
 - [ ] t_hvec sub_hvec (t_hvec, t_hvec)
 - [ ] t_hvec scale_hvec (t_hvec, float)
 - [ ] t_hvec normalize_hvec (t_hvec)
 - [ ] float dot_hvec (t_hvec, t_hvec) // ignore 4th dimension

t_rgb - color type {int red, int green, int blue}
 - [ ] t_rgb add_rgb (t_rgb, t_rgb)
 - [ ] t_rgb sub_rgb (t_rgb, t_rgb)
 - [ ] t_rgb mult_rgb (t_rgb, t_rgb) - Multiply rgb values
 - [ ] t_rgb scale_rgb (t_rgb, float)
 - [ ] t_rgb interpolate (t_rgb, t_rgb, float)
 - [ ] t_color convert_rgb (t_rgb)

t_color (defined in libft and used in mlx) is just {int alpha, t_rgb color}

t_transform - a 4x4 matrix for transformations
 - [ ] t_transform mat_multiply (t_transform, t_transform) - Schoolbook simple multiplication
 - [ ] t_vec3 transform_location (t_transform, t_vec3) [or is it for hvec??]
 - [ ] t_vec3 transform_direction (t_transform, t_vec3)
 - [ ] t_vec3 transform_surface_normal (t_transform, t_vec3)

t_image - mlx image matrix (t_color[HEIGHT][WIDTH] where the parameters are defined as preprocessor constants)

**Comment by Zunon** [comment]
Implemented in 074053b9c51d794ebe351ac6d36bb3376b5969b5
